spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/quartztest
    username: ammner
    password: ammner
    
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 5132
  

    